modLoader = "javafml"
loaderVersion = "[39,)"
issueTrackerURL = "https://github.com/CoffeeCatRailway/Plus/issues"
license = "GPLv3"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "CoffeeCatRailway"
credits = "Nyctoniac"
description = '''
Minceraft plus some stuffs!

Disclaimer: I only upload to https://www.curseforge.com & https://modrinth.com
Discord: https://discord.com/invite/JM4NjRzZPS
'''
updateJSONURL = "https://raw.githubusercontent.com/CoffeeCatRailway/Plus/main/update_checker.json"
logoFile = "icon.png"

[[dependencies.${id}]]
modId = "forge"
mandatory = true
versionRange = "[39,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "pollen"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${id}]]
modId = "jei"
mandatory = false
versionRange = "[9,)"
ordering = "BEFORE"
side = "BOTH"

[[dependencies.${id}]]
modId = "curios"
mandatory = false
versionRange = "[1.18.1-5,)"
ordering = "BEFORE"
side = "BOTH"