modLoader="javafml"
loaderVersion="[36,)"
license="https://www.gnu.org/licenses/gpl-3.0.en.html"
issueTrackerURL="https://github.com/CoffeeCatRailway/Plus/issues"

[[mods]]
modId="${modId}"
version="${modVersion}"
displayName="Plus"
logoFile="logo.png"
updateJSONURL="https://raw.githubusercontent.com/CoffeeCatRailway/Plus/main/update_checker.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/plus"
authors="${modAuthor}"
#credits="ManWithoutTaste for mouse model & any others who've helped!"
description='''
Minceraft plus some stuffs

Discord: https://discord.com/invite/JM4NjRzZPS
'''

[modproperties.${modId}]
catalogueItemIcon="minecraft:air"

[[dependencies.${modId}]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"
[[dependencies.${modId}]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"
#[[dependencies.hamncheese]]
#modId="jei"
#mandatory=false
#versionRange="[7,]"
#ordering="NONE"
#side="CLIENT"