@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.github.coffeecatrailway.plus.registry;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;