@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.github.coffeecatrailway.plus.common.enchantment;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;